# Generated by Django 2.2.6 on 2019-10-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
